# Form implementation generated from reading ui file '.\doctor_app_page.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox

import db_connect as db
import doctor_functions as df
from doctor_auth import validate_input


class Ui_Form(object):
    def __init__(self):
        self.doctor_name = ""
        self.doctor_data = None
        self.config = None
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(541, 410)
        self.logo_label = QtWidgets.QLabel(parent=Form)
        self.logo_label.setGeometry(QtCore.QRect(370, 40, 151, 101))
        self.logo_label.setText("")
        self.logo_label.setPixmap(QtGui.QPixmap(".\\logo.png"))
        self.logo_label.setScaledContents(True)
        self.logo_label.setObjectName("logo_label")

        self.app_title_label = QtWidgets.QLabel(parent=Form)
        self.app_title_label.setGeometry(QtCore.QRect(210, 40, 131, 41))
        self.app_title_label.setObjectName("app_title_label")

        self.message_label = QtWidgets.QLabel(parent=Form)
        self.message_label.setGeometry(QtCore.QRect(60, 130, 81, 21))
        self.message_label.setObjectName("message_label")

        self.request_label = QtWidgets.QLabel(parent=Form)
        self.request_label.setGeometry(QtCore.QRect(50, 170, 391, 16))
        self.request_label.setObjectName("request_label")

        self.add_patient_radioButton = QtWidgets.QRadioButton(parent=Form)
        self.add_patient_radioButton.setGeometry(QtCore.QRect(50, 210, 191, 31))
        self.add_patient_radioButton.setObjectName("add_patient_radioButton")
        self.add_patient_radioButton.toggled.connect(self.option_selected)  # Connect radio button to method

        self.transfer_patient_radioButton = QtWidgets.QRadioButton(parent=Form)
        self.transfer_patient_radioButton.setGeometry(QtCore.QRect(50, 250, 151, 21))
        self.transfer_patient_radioButton.setObjectName("transfer_patient_radioButton")
        self.transfer_patient_radioButton.toggled.connect(self.option_selected)  # Connect radio button to method


        self.refferal_radioButton = QtWidgets.QRadioButton(parent=Form)
        self.refferal_radioButton.setGeometry(QtCore.QRect(50, 290, 161, 16))
        self.refferal_radioButton.setObjectName("refferal_radioButton")
        self.refferal_radioButton.toggled.connect(self.option_selected)  # Connect radio button to method

        self.select_button = QtWidgets.QPushButton(parent=Form)
        self.select_button.setGeometry(QtCore.QRect(80, 320, 75, 24))
        self.select_button.setObjectName("select_button")
        self.select_button.clicked.connect(self.select_option)


        self.logout_button = QtWidgets.QPushButton(parent=Form)
        self.logout_button.setGeometry(QtCore.QRect(210, 360, 75, 24))
        self.logout_button.setObjectName("logout_button")
        self.logout_button.clicked.connect(self.logout)  #Connect select button to logout function


        self.cnp_label = QtWidgets.QLabel(parent=Form)
        self.cnp_label.setGeometry(QtCore.QRect(290, 200, 61, 16))
        self.cnp_label.setObjectName("cnp_label")
        self.cnp_label.hide()

        self.patient_name_label = QtWidgets.QLabel(parent=Form)
        self.patient_name_label.setGeometry(QtCore.QRect(290, 240, 61, 21))
        self.patient_name_label.setObjectName("patient_name_label")
        self.patient_name_label.hide()

        self.CNP_lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.CNP_lineEdit.setGeometry(QtCore.QRect(370, 200, 113, 21))
        self.CNP_lineEdit.setObjectName("CNP_lineEdit")
        self.CNP_lineEdit.hide()

        self.patient_name_lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.patient_name_lineEdit.setGeometry(QtCore.QRect(370, 240, 113, 21))
        self.patient_name_lineEdit.setObjectName("patient_name_lineEdit")
        self.patient_name_lineEdit.hide()

        self.spec_label = QtWidgets.QLabel("Specialization:", parent=Form)
        self.spec_label.setGeometry(QtCore.QRect(280, 270, 71, 19))
        self.spec_input = QtWidgets.QLineEdit(parent=Form)
        self.spec_input.setGeometry(QtCore.QRect(370, 270, 113, 21))
        self.spec_label.hide()
        self.spec_input.hide()

        self.gender_label = QtWidgets.QLabel("Gender:", parent=Form)
        self.gender_label.setGeometry(QtCore.QRect(290, 270, 61, 21))
        self.gender_label.setObjectName("gender_label")
        self.gender_label.hide()

        self.gender_comboBox = QtWidgets.QComboBox(parent=Form)
        self.gender_comboBox.setGeometry(QtCore.QRect(370, 270, 113, 21))
        self.gender_comboBox.setObjectName("gender_comboBox")
        self.gender_comboBox.addItem("F")
        self.gender_comboBox.addItem("M")
        self.gender_comboBox.hide()

        self.clinic_label = QtWidgets.QLabel("Clinic:", parent=Form)
        self.clinic_label.setGeometry(QtCore.QRect(280, 310, 71, 19))
        self.clinic_input = QtWidgets.QLineEdit(parent=Form)
        self.clinic_input.setGeometry(QtCore.QRect(370, 310, 113, 21))
        self.clinic_label.hide()
        self.clinic_input.hide()

        self.doctor_name_textEdit = QtWidgets.QTextEdit(parent=Form)
        self.doctor_name_textEdit.setGeometry(QtCore.QRect(150, 131, 121, 20))
        self.doctor_name_textEdit.setObjectName("doctor_name_textEdit")

        self.create_button = QtWidgets.QPushButton(parent=Form)
        self.create_button.setGeometry(QtCore.QRect(390, 360, 100, 24))
        self.create_button.setObjectName("create_button")
        self.create_button.hide()
        self.create_button.clicked.connect(self.create_referral)

        self.doctor_name_textEdit.setReadOnly(True)
        self.update_welcome_message()
        self.select_button.clicked.connect(self.select_option)
        self.retranslateUi(Form)

        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.app_title_label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:700; color:#0055ff;\">Medical Registry</span></p></body></html>"))
        self.message_label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:700;\">Welcome, Dr</span></p></body></html>"))
        self.request_label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:700;\">Please select the desired option, what do you need help with?</span></p></body></html>"))
        self.add_patient_radioButton.setText(_translate("Form", "Add a new patient"))
        self.transfer_patient_radioButton.setText(_translate("Form", "Transfer a patient"))
        self.refferal_radioButton.setText(_translate("Form", "Create refferal ticket"))
        self.select_button.setText(_translate("Form", "Select"))
        self.logout_button.setText(_translate("Form", "Logout"))
        self.cnp_label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt; font-weight:700;\">CNP</span></p></body></html>"))
        self.patient_name_label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt; font-weight:700;\">Name</span></p></body></html>"))
        self.spec_label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt; font-weight:700;\">Specialization</span></p></body></html>"))
        self.clinic_label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt; font-weight:700;\">Clinic</span></p></body></html>"))
        self.create_button.setText(_translate("Form", "Create"))
        self.gender_label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt; font-weight:700;\">Gender</span></p></body></html>"))


    def set_doctor_data(self, doctor_data, config):

        """Set the doctor data and update the welcome message."""

        self.doctor_data = doctor_data
        self.doctor_name = doctor_data['doctor_name']
        self.config = config
        self.update_welcome_message()

    def update_welcome_message(self):

        """Update the welcome message with the doctor's name."""

        self.doctor_name_textEdit.setText(self.doctor_name)

    def option_selected(self):

        """Show the select button when an option is selected"""

        self.select_button.setEnabled(True)

    def select_option(self):

        """Display the appropriate input fields based on the selected option."""

        if self.add_patient_radioButton.isChecked():
            self.add_patient_setup()
        elif self.transfer_patient_radioButton.isChecked():
            self.transfer_patient_setup()
        elif self.refferal_radioButton.isChecked():
            self.referral_setup()

    def transfer_patient_setup(self):

        """Set up the UI elements for transferring a patient."""

        self.cnp_label.show()
        self.CNP_lineEdit.show()
        self.create_button.show()
        self.create_button.setText("Transfer Patient")
        self.patient_name_label.show()
        self.patient_name_lineEdit.show()
        self.gender_label.hide()
        self.gender_comboBox.hide()
        self.clinic_label.hide()
        self.clinic_input.hide()
        self.spec_label.hide()
        self.spec_input.hide()
        self.create_button.clicked.disconnect()
        self.create_button.clicked.connect(self.transfer_patient)

    def transfer_patient(self):
        """Connect the transfer function for the current doctor."""

        cnp = self.CNP_lineEdit.text().strip()
        name = self.patient_name_lineEdit.text().strip()
        new_doctor_id = self.doctor_data['doctor_id']

        config = db.read_config()
        result = df.transfer_patient(config, cnp, name, new_doctor_id)

        if isinstance(result, dict):  # Successful transfer returns a dictionary
            QMessageBox.information(None, "Patient Transferred",
                                    f"Patient {result['name']} was successfully transferred to you with ID: {result['patient_id']}")
            self.CNP_lineEdit.clear()
            self.patient_name_lineEdit.clear()
        else:
            QMessageBox.warning(None, "Error Transferring Patient", result)

    def referral_setup(self):

        """Set up the UI elements for creating a referral."""

        self.cnp_label.show()
        self.patient_name_label.show()
        self.CNP_lineEdit.show()
        self.CNP_lineEdit.clear()
        self.patient_name_lineEdit.show()
        self.patient_name_lineEdit.clear()
        self.spec_label.show()
        self.spec_input.show()
        self.clinic_label.show()
        self.clinic_input.show()
        self.create_button.show()
        self.gender_label.hide()
        self.gender_comboBox.hide()
        self.create_button.setText("Create Referral")
        self.create_button.clicked.disconnect()  # Ensure the button is disconnected before connecting
        self.create_button.clicked.connect(self.create_referral)

    def create_referral(self):

        """Create a referral ticket."""

        patient_name = self.patient_name_lineEdit.text().strip()
        patient_cnp = self.CNP_lineEdit.text().strip()
        specialization = self.spec_input.text().strip()
        clinic = self.clinic_input.text().strip()
        current_doctor_id = self.doctor_data['doctor_id']

        if not all([patient_name, patient_cnp, specialization, clinic]):
            QMessageBox.warning(None, "Error", "Please fill in all fields.")
            return False

        result = df.create_referral(self.config, patient_name, patient_cnp, specialization, clinic, current_doctor_id)

        if result is True:
            QMessageBox.information(None, "Success", "Referral ticket created successfully.")
            self.create_referral_setup()

        else:
            QMessageBox.warning(None, "Error", result)


    def create_referral_setup(self):

        """Clear the input fields after a successful referral"""

        self.patient_name_lineEdit.clear()
        self.CNP_lineEdit.clear()
        self.spec_input.clear()
        self.clinic_input.clear()

    def add_patient_setup(self):

        """Set up the UI elements for adding a new patient."""

        self.cnp_label.show()
        self.patient_name_label.show()
        self.CNP_lineEdit.show()
        self.patient_name_lineEdit.show()
        self.gender_comboBox.show()
        self.gender_label.show()
        self.create_button.show()
        self.create_button.setText("Add Patient")
        self.create_button.clicked.disconnect()  # Disconnect any previous connections
        self.create_button.clicked.connect(self.add_patient)  # Connect to add_patient function

        # Hide referral-specific elements
        self.spec_label.hide()
        self.spec_input.hide()
        self.clinic_label.hide()
        self.clinic_input.hide()

    def add_patient(self):

        """Add a new patient to the database."""

        name = self.patient_name_lineEdit.text().strip()
        cnp = self.CNP_lineEdit.text().strip()
        gender = self.gender_comboBox.currentText()
        doctor_id = self.doctor_data['doctor_id']

        config = db.read_config()
        result = df.add_new_patient(config, name, cnp, gender, doctor_id)

        if isinstance(result, int):  # Successful addition returns patient ID
            QMessageBox.information(None, "Patient Added", f"Patient {name} was successfully added with ID: {result}")
            self.patient_name_lineEdit.clear()
            self.CNP_lineEdit.clear()
            self.gender_comboBox.setCurrentIndex(0)
        else:  # Validation error or any other error
            QMessageBox.warning(None, "Error Adding Patient", result)

    def logout(self):

        """Logout from the application."""

        QtWidgets.QApplication.quit()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
