# Form implementation generated from reading ui file '.\login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from doctor_app_page import Ui_Form as DoctorForm
import json
from admin_app_page import Ui_Form as AdminForm
import db_connect as db
from doctor_auth import doctor_login


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(592, 441)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.username_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.username_label.setGeometry(QtCore.QRect(60, 150, 61, 21))
        self.username_label.setObjectName("username_label")

        self.password_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.password_label.setGeometry(QtCore.QRect(60, 190, 61, 16))
        self.password_label.setObjectName("password_label")


        self.admin_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.admin_pushButton.setGeometry(QtCore.QRect(160, 240, 75, 24))
        self.admin_pushButton.setObjectName("admin_pushButton")
        self.admin_pushButton.clicked.connect(self.admin_login)

        self.username_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.username_lineEdit.setGeometry(QtCore.QRect(140, 150, 113, 21))
        self.username_lineEdit.setObjectName("username_lineEdit")

        self.password_lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.password_lineEdit_2.setGeometry(QtCore.QRect(140, 190, 113, 21))
        self.password_lineEdit_2.setObjectName("password_lineEdit_2")
        self.password_lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)

        self.logo_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.logo_label.setGeometry(QtCore.QRect(380, 10, 151, 101))
        self.logo_label.setText("")
        self.logo_label.setPixmap(QtGui.QPixmap(".\\logo.png"))
        self.logo_label.setScaledContents(True)
        self.logo_label.setObjectName("logo_label")

        self.app_title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.app_title_label.setGeometry(QtCore.QRect(200, 30, 131, 41))
        self.app_title_label.setObjectName("app_title_label")

        self.admin_label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.admin_label_2.setGeometry(QtCore.QRect(160, 110, 61, 21))
        self.admin_label_2.setObjectName("admin_label_2")

        self.doctor_cnp_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.doctor_cnp_label.setGeometry(QtCore.QRect(310, 190, 61, 16))
        self.doctor_cnp_label.setObjectName("doctor_cnp_label")

        self.CNP_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.CNP_lineEdit.setGeometry(QtCore.QRect(390, 190, 113, 21))
        self.CNP_lineEdit.setObjectName("CNP_lineEdit")
        self.CNP_lineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)


        self.doctor_name_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.doctor_name_lineEdit.setGeometry(QtCore.QRect(390, 150, 113, 21))
        self.doctor_name_lineEdit.setObjectName("doctor_name_lineEdit")

        self.doctor_name_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.doctor_name_label.setGeometry(QtCore.QRect(310, 150, 61, 21))
        self.doctor_name_label.setObjectName("doctor_name_label")

        self.doctor_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.doctor_label.setGeometry(QtCore.QRect(410, 110, 61, 21))
        self.doctor_label.setObjectName("doctor_label")

        self.doctor_login_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.doctor_login_pushButton.setGeometry(QtCore.QRect(410, 240, 75, 24))
        self.doctor_login_pushButton.setObjectName("doctor_login_pushButton")
        self.doctor_login_pushButton.clicked.connect(self.doctor_login)

        self.logout_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.logout_button.setGeometry(QtCore.QRect(250, 360, 75, 24))
        self.logout_button.setObjectName("logout_button")
        self.logout_button.clicked.connect(self.logout)  # Connect select button to logout function

        self.MainWindow = MainWindow
        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 592, 22))
        self.menubar.setObjectName("menubar")

        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.username_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:700;\">Username</span></p></body></html>"))
        self.password_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:700;\">Password</span></p></body></html>"))
        self.admin_pushButton.setText(_translate("MainWindow", "Login"))
        self.app_title_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:700; color:#0055ff;\">Medical Registry</span></p></body></html>"))
        self.admin_label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:700;\">Admin</span></p></body></html>"))
        self.doctor_cnp_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:700;\">CNP</span></p></body></html>"))
        self.doctor_name_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:700;\">Name</span></p></body></html>"))
        self.doctor_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:700;\">Doctor</span></p></body></html>"))
        self.doctor_login_pushButton.setText(_translate("MainWindow", "Login"))
        self.logout_button.setText(_translate("Form", "Logout"))



    def admin_login(self):

        """Connect admin_login function by adding his username and password"""

        username = self.username_lineEdit.text()
        password = self.password_lineEdit_2.text()

        if not username or not password:
            QtWidgets.QMessageBox.warning(None, "Input Error", "Please enter both username and password.")
            return False

        # Read admin credentials from config file
        try:
            with open("admin_config.json", "r") as f:
                admin_credentials = json.load(f)
        except Exception as e:
            QtWidgets.QMessageBox.critical(None, "Error", f"Failed to read admin credentials: {e}")
            return False

        if username == admin_credentials['username'] and password == admin_credentials['password']:
            QtWidgets.QMessageBox.information(None, "Login Successful", "Welcome, Admin!")
            self.open_admin_page()
        else:
            QtWidgets.QMessageBox.warning(None, "Login Failed", "Invalid username or password. Please try again.")



    def open_admin_page(self):

        """Create a new QWidget for the admin page and set up the UI for the admin window"""
        self.admin_window = QtWidgets.QWidget()
        self.admin_ui = AdminForm()
        self.admin_ui.setupUi(self.admin_window)

        self.admin_window.show()
        self.MainWindow.hide()

    def doctor_login(self):

        """Connect login function by adding name and CNP """

        cnp = self.CNP_lineEdit.text().strip()
        name = self.doctor_name_lineEdit.text().strip()

        config = db.read_config()
        login_result = doctor_login(config, cnp, name)

        if isinstance(login_result, dict):
            QtWidgets.QMessageBox.information(None, "Login Successful", f"Welcome, Dr. {name}!")
            self.open_doctor_page(login_result)
        else:
            QtWidgets.QMessageBox.warning(None, "Login Failed", login_result)

    def open_doctor_page(self, doctor_data):

        """Create a new QWidget for the doctor page and set up the UI for the doctor window
               Pass the doctor data and config to the doctor UI"""

        self.doctor_window = QtWidgets.QWidget()
        self.doctor_ui = DoctorForm()
        self.doctor_ui.setupUi(self.doctor_window)
        config = db.read_config()  # Read the database configuration
        self.doctor_ui.set_doctor_data(doctor_data, config)  # Pass both doctor_data and config

        self.doctor_window.show()
        self.MainWindow.hide()

    def logout(self):

        """Create function to close the application"""

        QtWidgets.QApplication.quit()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
